export const GET_COURSE_LIST_REQUEST = 'GET_COURSE_LIST_REQUEST';
export const GET_COURSE_LIST_SUCCESS = 'GET_COURSE_LIST_SUCCESS';
export const GET_COURSE_LIST_FAIL = 'GET_COURSE_LIST_FAIL';

export const GET_TOP_COURSES_REQUEST = 'GET_TOP_COURSES_REQUEST';
export const GET_TOP_COURSES_SUCCESS = 'GET_TOP_COURSES_SUCCESS';
export const GET_TOP_COURSES_FAIL = 'GET_TOP_COURSES_FAIL';

export const GET_COURSE_CATEGORY_LIST_REQUEST =
  'GET_COURSE_CATEGORY_LIST_REQUEST';
export const GET_COURSE_CATEGORY_LIST_SUCCESS =
  'GET_COURSE_CATEGORY_LIST_SUCCESS';
export const GET_COURSE_CATEGORY_LIST_FAIL = 'GET_COURSE_CATEGORY_LIST_FAIL';

export const GET_COURSE_DETAILS_REQUEST = 'GET_COURSE_DETAILS_REQUEST';
export const GET_COURSE_DETAILS_SUCCESS = 'GET_COURSE_DETAILS_SUCCESS';
export const GET_COURSE_DETAILS_FAIL = 'GET_COURSE_DETAILS_FAIL';

export const ADD_COURSE_REVIEW_REQUEST = 'ADD_COURSE_REVIEW_REQUEST';
export const ADD_COURSE_REVIEW_SUCCESS = 'ADD_COURSE_REVIEW_SUCCESS';
export const ADD_COURSE_REVIEW_FAIL = 'ADD_COURSE_REVIEW_FAIL';
export const ADD_COURSE_REVIEW_RESET = 'ADD_COURSE_REVIEW_RESET';
