export const GET_COURSE_LIST_REQUEST = 'GET_COURSE_LIST_REQUEST';
export const GET_COURSE_LIST_SUCCESS = 'GET_COURSE_LIST_SUCCESS';
export const GET_COURSE_LIST_FAIL = 'GET_COURSE_LIST_FAIL';

export const GET_COURSE_CATEGORY_LIST_REQUEST =
  'GET_COURSE_CATEGORY_LIST_REQUEST';
export const GET_COURSE_CATEGORY_LIST_SUCCESS =
  'GET_COURSE_CATEGORY_LIST_SUCCESS';
export const GET_COURSE_CATEGORY_LIST_FAIL = 'GET_COURSE_CATEGORY_LIST_FAIL';

export const GET_COURSE_DETAILS_REQUEST = 'GET_COURSE_DETAILS_REQUEST';
export const GET_COURSE_DETAILS_SUCCESS = 'GET_COURSE_DETAILS_SUCCESS';
export const GET_COURSE_DETAILS_FAIL = 'GET_COURSE_DETAILS_FAIL';
