export const GET_INSTRUCTOR_LIST_REQUEST = 'GET_INSTRUCTOR_LIST_REQUEST';
export const GET_INSTRUCTOR_LIST_SUCCESS = 'GET_INSTRUCTOR_LIST_SUCCESS';
export const GET_INSTRUCTOR_LIST_FAIL = 'GET_INSTRUCTOR_LIST_FAIL';

export const GET_INSTRUCTOR_DETAILS_REQUEST = 'GET_INSTRUCTOR_DETAILS_REQUEST';
export const GET_INSTRUCTOR_DETAILS_SUCCESS = 'GET_INSTRUCTOR_DETAILS_SUCCESS';
export const GET_INSTRUCTOR_DETAILS_FAIL = 'GET_INSTRUCTOR_DETAILS_FAIL';
